version = "v0.7.0"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.7.0/hmt-frontend-toy-v0.7.0-aarch64-unknown-linux-gnu.tar.gz"
hash = "92ccefcd1aef2c0da5239b7c9d514fa6f6a5bd4a4b2de6d9232faff3a6a56d4c"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.7.0/hmt-frontend-toy-v0.7.0-x86_64-apple-darwin.tar.gz"
hash = "9116e9fb7334f0e1754942f93063faa785b6285a9a46f2d68473d7255658dbca"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.7.0/hmt-frontend-toy-v0.7.0-aarch64-apple-darwin.tar.gz"
hash = "6109a897d0ad8e0824a295f8fea0e8f9390992fe5e6ae18447a0b9d188816bb5"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.7.0/hmt-frontend-toy-v0.7.0-x86_64-unknown-linux-gnu.tar.gz"
hash = "1d711645f50716c91f19b10ed89816bd3fec31d9efcc0b81d0a3d3ece57b3263"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/hmt-frontend-toy/releases/download/v0.7.0/hmt-frontend-toy-v0.7.0-x86_64-pc-windows-msvc.tar.gz"
hash = "654488e287f5fbbe7a75a016d2dbc9130e906d2d05adc9616679ea3b2b7cc907"
